version: "3.9"

services:
  db:
    image: postgres:13
    container_name: nforgot-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nforgot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
     # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  db_data: