name: Deploy nforgot-api

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd api
          npm install
          npm install -g typescript

      - name: Build project with TypeScript
        run: |
          pwd
          npm run build

      - name: Login Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t furqas/nforgot-api -f .api/Dockerfile .

      - name: Push image docker
        run: docker push furqas/nforgot-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull furqas/nforgot-api:latest

      - name: Remove docker container (if exists)
        run: sudo docker rm -f nforgot-api || true

      - name: Run docker container
        run: |
          sudo docker run -d \
            -p 3333:3333 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --name nforgot-api \
            furqas/nforgot-api
